config/routes.rb
Rails.application.routes.draw do
  resources :toys
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/dogs" => "dogs#index"
  get "/dogs/new" => "dogs#new"
  post "/dogs" => "dogs#create"
  get "/dogs/:id" => "dogs#show"
  get "/dogs/:id/edit" => "dogs#edit"
  patch "/dogs/:id" => "dogs#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many :toys
end

app/models/toy.rb
class Toy < ApplicationRecord
  belongs_to :dog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def index
    @dogs = Dog.all
    render "/dogs/index"
  end

  def show
    @dog = Dog.find_by(id: params[:id])
    render "/dogs/show"
  end
  
  def new
    render "/dogs/new"
  end

  def create
    dog = Dog.new(
      name: params[:name],
      breed: params[:breed],
      age: params[:age],
      image_url: params[:image_url]
    )
    dog.save
    redirect_to "/dogs"
  end

  def edit
    render "/dogs/edit"
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_action :set_toy, only: %i[ show edit update destroy ]

  # GET /toys or /toys.json
  def index
    @toys = Toy.all
  end

  # GET /toys/1 or /toys/1.json
  def show
  end

  # GET /toys/new
  def new
    @toy = Toy.new
  end

  # GET /toys/1/edit
  def edit
  end

  # POST /toys or /toys.json
  def create
    @toy = Toy.new(toy_params)

    respond_to do |format|
      if @toy.save
        format.html { redirect_to toy_url(@toy), notice: "Toy was successfully created." }
        format.json { render :show, status: :created, location: @toy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /toys/1 or /toys/1.json
  def update
    respond_to do |format|
      if @toy.update(toy_params)
        format.html { redirect_to toy_url(@toy), notice: "Toy was successfully updated." }
        format.json { render :show, status: :ok, location: @toy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toys/1 or /toys/1.json
  def destroy
    @toy.destroy

    respond_to do |format|
      format.html { redirect_to toys_url, notice: "Toy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_toy
      @toy = Toy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def toy_params
      params.require(:toy).permit(:name, :description, :price, :dog_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/dogs/edit.html.erb
<h1> This is the Edit Page!!!!!!

app/views/dogs/index.html.erb
<h1>This is the dogs index page!!</h1> 

<% @dogs.each do |dog| %>
<p>name: <a href="/dogs/<%= dog.id %>"><%= dog.name %></a> </p>
<img src="<%= dog.image_url%>" >
<hr/>
<% end %>

app/views/dogs/new.html.erb
<h1> This is the new Page!!!</h1>

 <form action="/dogs" method="post">
   <p> Name: <input type="text" name="name">
   <p> Breed: <input type="text" name="breed">
   <p> Age: <input type="text" name="age">
   <p> Image URL: <input type="text" name="image_url">
   <input type="submit">
 </form>

app/views/dogs/show.html.erb
<h1> This is the show page </h1>

<p>name: <%=@dog.name%></p>
<p>age: <%=@dog.age%></p>
<p>breed: <%=@dog.breed%></p>
<img src="<%= @dog.image_url%>" >

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogFullstackApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <a href="/dogs">Home</a>
    <a href="/dogs/new">New dog</a>
    <%= yield %>
  </body>
</html>

app/views/toys/_form.html.erb
<%= form_with(model: toy) do |form| %>
  <% if toy.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(toy.errors.count, "error") %> prohibited this toy from being saved:</h2>

      <ul>
        <% toy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :dog_id, style: "display: block" %>
    <%= form.text_field :dog_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/toys/_toy.html.erb
<div id="<%= dom_id toy %>">
  <p>
    <strong>Name:</strong>
    <%= toy.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= toy.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= toy.price %>
  </p>

  <p>
    <strong>Dog:</strong>
    <%= toy.dog_id %>
  </p>

</div>

app/views/toys/edit.html.erb
<h1>Editing toy</h1>

<%= render "form", toy: @toy %>

<br>

<div>
  <%= link_to "Show this toy", @toy %> |
  <%= link_to "Back to toys", toys_path %>
</div>

app/views/toys/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Toys</h1>

<div id="toys">
  <% @toys.each do |toy| %>
    <%= render toy %>
    <p>
      <%= link_to "Show this toy", toy %>
    </p>
  <% end %>
</div>

<%= link_to "New toy", new_toy_path %>

app/views/toys/new.html.erb
<h1>New toy</h1>

<%= render "form", toy: @toy %>

<br>

<div>
  <%= link_to "Back to toys", toys_path %>
</div>

app/views/toys/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @toy %>

<div>
  <%= link_to "Edit this toy", edit_toy_path(@toy) %> |
  <%= link_to "Back to toys", toys_path %>

  <%= button_to "Destroy this toy", @toy, method: :delete %>
</div>